list=[453,345,3,543,54356]
for i in range(0,6):
  print(list[i])

#if the range is not there  for 6 value  then that will give error
"""
Traceback (most recent call last):
   File "list_in_for_loop.py", line 3, in <module>
       print(list[i])
IndexError: list index out of range
""" 
